/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Producto;
import java.util.ArrayList;
import Controlador.DetalleVentaData;
import Controlador.ProductoData;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristina Ferez
 */
public class InventarioProductosView extends javax.swing.JInternalFrame {

    private ProductoData productoData = new ProductoData();
    private DetalleVentaData detalleVentaData = new DetalleVentaData();
    private ArrayList<Producto> lista;
    private DefaultTableModel tabla;

    /**
     * Creates new form Inventario
     */
    public InventarioProductosView() {
        initComponents();
          jRbCategoria.setSelected(true);
        tabla = new DefaultTableModel();
        armarTabla();
        lista = (ArrayList<Producto>) productoData.listar();
        llenarTabla(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRbCategoria = new javax.swing.JRadioButton();
        jRbNombre = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("INVENTARIO");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jRbCategoria.setText("Categoria");
        jRbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbCategoriaActionPerformed(evt);
            }
        });

        jRbNombre.setText("Nombre");
        jRbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(btnBuscar)
                        .addGap(71, 71, 71)
                        .addComponent(jBLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jRbCategoria)
                        .addGap(90, 90, 90)
                        .addComponent(jRbNombre)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbCategoria)
                    .addComponent(jRbNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jBLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
           if(jRbCategoria.isSelected()){
                lista=(ArrayList<Producto>)productoData.buscarProductosCoincidenciaPorCateg(jTextBuscar.getText());
                llenarTabla(lista);
            }
            if(lista.isEmpty()){
                JOptionPane.showMessageDialog(this, "No hay productos");
       }
       if(jRbNombre.isSelected()){
                lista=(ArrayList<Producto>)productoData.buscarProductosCoincidenciaPorNombre(jTextBuscar.getText());
                llenarTabla(lista);
            }
            if(lista.isEmpty()){
                JOptionPane.showMessageDialog(this, "No hay productos");
           
       }
        if(jTextBuscar.getText().trim().equals("")){
    JOptionPane.showMessageDialog(this, "Llene el campo");
            
}
            
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        jTextBuscar.setText("");
        lista = (ArrayList<Producto>) productoData.listar();
        llenarTabla(lista);
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jRbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbCategoriaActionPerformed
        // TODO add your handling code here:
        borrarFilas();
    }//GEN-LAST:event_jRbCategoriaActionPerformed

    private void jRbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbNombreActionPerformed
        // TODO add your handling code here:
        borrarFilas();
    }//GEN-LAST:event_jRbNombreActionPerformed

    
    
    ///////////////////////////////////////////////////////////////////////////////////////////////////
    private void armarTabla() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("NOMBRE");
        columnas.add("CATEGORIA");
        columnas.add("DESCRIPCION");
        columnas.add("PRECIO");
        columnas.add("STOCK");

        for (Object i : columnas) {
            tabla.addColumn(i);
            jTable1.setModel(tabla);
        }
    }

    private void llenarTabla(ArrayList<Producto> lista) {
        borrarFilas();
        if (lista.isEmpty()) {
            return;
        }
        for (Producto prod : lista) {
            tabla.addRow(new Object[]{prod.getNombre(), prod.getCategoria(), prod.getDescripcion(), prod.getPrecioActual(), prod.getStock()});
        }
    }

    public void borrarFilas() {
        int i = tabla.getRowCount() - 1;
        for (int j = i; j >= 0; j--) {
            tabla.removeRow(j);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRbCategoria;
    private javax.swing.JRadioButton jRbNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextBuscar;
    // End of variables declaration//GEN-END:variables
}
