/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        EscritorioPrinc = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        ClienteView = new javax.swing.JMenuItem();
        listaClientes = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        listaVentas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        RegistrarProducto = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        SalirSistema = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        EscritorioPrinc.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout EscritorioPrincLayout = new javax.swing.GroupLayout(EscritorioPrinc);
        EscritorioPrinc.setLayout(EscritorioPrincLayout);
        EscritorioPrincLayout.setHorizontalGroup(
            EscritorioPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        EscritorioPrincLayout.setVerticalGroup(
            EscritorioPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        jMenu4.setText("Clientes");

        ClienteView.setText("Administrar clientes");
        ClienteView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteViewActionPerformed(evt);
            }
        });
        jMenu4.add(ClienteView);

        listaClientes.setText("LIsta de clientes");
        listaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientesActionPerformed(evt);
            }
        });
        jMenu4.add(listaClientes);

        jMenuBar2.add(jMenu4);

        jMenu8.setText("Ventas");

        listaVentas.setText("Administrar Ventas");
        listaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVentasActionPerformed(evt);
            }
        });
        jMenu8.add(listaVentas);

        jMenuBar2.add(jMenu8);

        jMenu6.setText("Inventario");

        RegistrarProducto.setText("Registrar producto");
        RegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProductoActionPerformed(evt);
            }
        });
        jMenu6.add(RegistrarProducto);

        jMenuItem5.setText("Lista de productos");
        jMenu6.add(jMenuItem5);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Proveedor");

        jMenuItem4.setText("Administrar Proveedores");
        jMenu7.add(jMenuItem4);

        jMenuItem1.setText("Lista de proveedores");
        jMenu7.add(jMenuItem1);

        jMenuBar2.add(jMenu7);

        jMenu5.setText("Compras");

        jMenuItem3.setText("Administrar Compras");
        jMenu5.add(jMenuItem3);

        jMenuBar2.add(jMenu5);

        jMenu10.setText("Salir");

        SalirSistema.setText("Salir del sistema");
        SalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirSistemaActionPerformed(evt);
            }
        });
        jMenu10.add(SalirSistema);

        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EscritorioPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EscritorioPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteViewActionPerformed
        // TODO add your handling code here:
        EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ClienteView clienteVw=new ClienteView();
        clienteVw.setVisible(true);
        EscritorioPrinc.add(clienteVw);
        EscritorioPrinc.moveToFront(clienteVw);
        
    }//GEN-LAST:event_ClienteViewActionPerformed

    private void SalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirSistemaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SalirSistemaActionPerformed

    private void RegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProductoActionPerformed
        // TODO add your handling code here:
        EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ProductoView productoVw= new ProductoView();
        productoVw.setVisible(true);
        EscritorioPrinc.add(productoVw);
        EscritorioPrinc.moveToFront(productoVw);
    }//GEN-LAST:event_RegistrarProductoActionPerformed

    private void listaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientesActionPerformed
        // TODO add your handling code here:
        EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ListaClientes listaClienteVw=new ListaClientes();
        listaClienteVw.setVisible(true);
        EscritorioPrinc.add(listaClienteVw);
        EscritorioPrinc.moveToFront(listaClienteVw);
    }//GEN-LAST:event_listaClientesActionPerformed

    private void listaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVentasActionPerformed
        // TODO add your handling code here:
        EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ListaVentas listaVentasView = new ListaVentas();
        listaVentasView.setVisible(true);
        EscritorioPrinc.add(listaVentasView);
        EscritorioPrinc.moveToFront(listaVentasView);        
    }//GEN-LAST:event_listaVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClienteView;
    public static javax.swing.JDesktopPane EscritorioPrinc;
    private javax.swing.JMenuItem RegistrarProducto;
    private javax.swing.JMenuItem SalirSistema;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem listaClientes;
    private javax.swing.JMenuItem listaVentas;
    // End of variables declaration//GEN-END:variables
}
