/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        EscritorioPrinc = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        ClienteView = new javax.swing.JMenuItem();
        listaClientes = new javax.swing.JMenuItem();
        Ventas = new javax.swing.JMenu();
        listaVentas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        RegistrarProducto = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Compras = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Compra = new javax.swing.JMenuItem();
        pro = new javax.swing.JMenu();
        proveedor = new javax.swing.JMenuItem();
        listaProveedores = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        listaVenras = new javax.swing.JMenuItem();
        Venta = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        EscritorioPrinc.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout EscritorioPrincLayout = new javax.swing.GroupLayout(EscritorioPrinc);
        EscritorioPrinc.setLayout(EscritorioPrincLayout);
        EscritorioPrincLayout.setHorizontalGroup(
            EscritorioPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        EscritorioPrincLayout.setVerticalGroup(
            EscritorioPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        jMenu4.setText("Clientes");

        ClienteView.setText("Administrar clientes");
        ClienteView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteViewActionPerformed(evt);
            }
        });
        jMenu4.add(ClienteView);

        listaClientes.setText("LIsta de clientes");
        listaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientesActionPerformed(evt);
            }
        });
        jMenu4.add(listaClientes);

        jMenuBar2.add(jMenu4);

        Ventas.setText("Ventas");

        listaVentas.setText("Administrar Ventas");
        listaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVentasActionPerformed(evt);
            }
        });
        Ventas.add(listaVentas);

        jMenuBar2.add(Ventas);

        jMenu6.setText("Inventario");

        RegistrarProducto.setText("Registrar producto");
        RegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarProductoActionPerformed(evt);
            }
        });
        jMenu6.add(RegistrarProducto);

        jMenuItem5.setText("Lista de productos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar2.add(jMenu6);

        Compras.setText("Compras");

        jMenuItem3.setText("Administrar Compras");
        Compras.add(jMenuItem3);

        Compra.setText("Compra");
        Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraActionPerformed(evt);
            }
        });
        Compras.add(Compra);

        jMenuBar2.add(Compras);

        pro.setText("Proveedor");

        proveedor.setText("Administrar Proveedores");
        proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorActionPerformed(evt);
            }
        });
        pro.add(proveedor);

        listaProveedores.setText("Lista de Proveedores");
        listaProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProveedoresActionPerformed(evt);
            }
        });
        pro.add(listaProveedores);

        jMenuBar2.add(pro);

        jMenu5.setText("Ventas");

        listaVenras.setText("Administrar Ventas");
        jMenu5.add(listaVenras);

        Venta.setText("Venta");
        Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaActionPerformed(evt);
            }
        });
        jMenu5.add(Venta);

        jMenuBar2.add(jMenu5);

        jMenu9.setText("Salir");

        Salir.setText("Salir del Sistema");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu9.add(Salir);

        jMenuBar2.add(jMenu9);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EscritorioPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EscritorioPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteViewActionPerformed
        // TODO add your handling code here:
        EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ClienteView clienteVw = new ClienteView();
        clienteVw.setVisible(true);
        EscritorioPrinc.add(clienteVw);
        EscritorioPrinc.moveToFront(clienteVw);

    }//GEN-LAST:event_ClienteViewActionPerformed

    private void RegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarProductoActionPerformed
          // TODO add your handling code here:
        EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ProductoView productoVw = new ProductoView();
        productoVw.setVisible(true);
        EscritorioPrinc.add(productoVw);
        EscritorioPrinc.moveToFront(productoVw);
    }//GEN-LAST:event_RegistrarProductoActionPerformed

    private void listaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientesActionPerformed
        // TODO add your handling code here:
        EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ListaClientes listaClienteVw = new ListaClientes();
        listaClienteVw.setVisible(true);
        EscritorioPrinc.add(listaClienteVw);
        EscritorioPrinc.moveToFront(listaClienteVw);
    }//GEN-LAST:event_listaClientesActionPerformed

    private void listaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVentasActionPerformed
        // TODO add your handling code here:
        EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ListaVentas listaVentasView = new ListaVentas();
        listaVentasView.setVisible(true);
        EscritorioPrinc.add(listaVentasView);
        EscritorioPrinc.moveToFront(listaVentasView);
    }//GEN-LAST:event_listaVentasActionPerformed

    private void listaProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProveedoresActionPerformed
        // TODO add your handling code here:
        EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ListaProveedores listaProView = new ListaProveedores();
        listaProView.setVisible(true);
        EscritorioPrinc.add(listaProView);
        EscritorioPrinc.moveToFront(listaProView);
    }//GEN-LAST:event_listaProveedoresActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorActionPerformed
        // TODO add your handling code here:
         EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        ProveedorView ProView = new ProveedorView();
        ProView.setVisible(true);
        EscritorioPrinc.add(ProView);
        EscritorioPrinc.moveToFront(ProView);
        
    }//GEN-LAST:event_proveedorActionPerformed

    private void CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraActionPerformed
        // TODO add your handling code here:
         EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        CompraView ComView = new CompraView();
        ComView.setVisible(true);
        EscritorioPrinc.add(ComView);
        EscritorioPrinc.moveToFront(ComView);
    }//GEN-LAST:event_CompraActionPerformed

    private void VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaActionPerformed
        // TODO add your handling code here:
         EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        VentaView venView = new VentaView();
        venView.setVisible(true);
        EscritorioPrinc.add(venView);
        EscritorioPrinc.moveToFront(venView);
    }//GEN-LAST:event_VentaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         EscritorioPrinc.removeAll();
        EscritorioPrinc.repaint();
        InventarioProductosView venView = new InventarioProductosView();
        venView.setVisible(true);
        EscritorioPrinc.add(venView);
        EscritorioPrinc.moveToFront(venView);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClienteView;
    private javax.swing.JMenuItem Compra;
    private javax.swing.JMenu Compras;
    public static javax.swing.JDesktopPane EscritorioPrinc;
    private javax.swing.JMenuItem RegistrarProducto;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem Venta;
    private javax.swing.JMenu Ventas;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem listaClientes;
    private javax.swing.JMenuItem listaProveedores;
    private javax.swing.JMenuItem listaVenras;
    private javax.swing.JMenuItem listaVentas;
    private javax.swing.JMenu pro;
    private javax.swing.JMenuItem proveedor;
    // End of variables declaration//GEN-END:variables
}
